// data.js - Zentrale Daten für Penny, Gänge, Rezepte & Standard-Produkte

const MARKET_AISLES = {
  'penny': [
    { id: 'a-1', number: 1, name: 'Gang 1: Obst, Gemüse & Fertigsalate', orderIndex: 1 },
    { id: 'a-2', number: 2, name: 'Gang 2: Chips, Knabberkram & Schokolade', orderIndex: 2 },
    { id: 'a-3', number: 3, name: 'Gang 3: Getränke (Wasser, Cola, Limonaden & Bier)', orderIndex: 3 },
    { id: 'a-4', number: 4, name: 'Gang 4: Haferflocken, Bio-Abteilung & Kaffee', orderIndex: 4 },
    { id: 'a-5', number: 5, name: 'Gang 5: Frischetheke mit Fleisch', orderIndex: 5 },
    { id: 'a-6', number: 6, name: 'Gang 6: Maggi Fix, Suppen, Gewürze, Nudeln, Reis, Eier & Öl', orderIndex: 6 },
    { id: 'a-7', number: 7, name: 'Gang 7: Milchprodukte, Fisch, Aufschnitt, Aufstriche & Käse', orderIndex: 7 },
    { id: 'a-8', number: 8, name: 'Gang 8: Dosenfisch, Gewürzgurten & haltbare Konserven', orderIndex: 8 },
    { id: 'a-9', number: 9, name: 'Gang 9: Milch, Butter, Margarine, Frikadellen & Snack-Würstchen', orderIndex: 9 },
    { id: 'a-10', number: 10, name: 'Gang 10: Brot- & Backwaren', orderIndex: 10 },
    { id: 'a-11', number: 11, name: 'Gang 11: Tiefkühlware (TK)', orderIndex: 11 },
    { id: 'a-12', number: 12, name: 'Gang 12: Drogerie & Tiernahrung', orderIndex: 12 },
    { id: 'a-13', number: 13, name: 'Gang 13: Spirituosen, Tabak & Kasse', orderIndex: 13 }
  ],
  'rewe': [
    { id: 'rw-1', number: 1, name: '1. Obst & Gemüse', orderIndex: 1 },
    { id: 'rw-2', number: 2, name: '2. Frischetheke (Fleisch, Wurst & Käse)', orderIndex: 2 },
    { id: 'rw-3', number: 3, name: '3. Molkereiprodukte & Milch', orderIndex: 3 },
    { id: 'rw-4', number: 4, name: '4. Backshop & Brotwaren', orderIndex: 4 },
    { id: 'rw-5', number: 5, name: '5. Trockensortiment (Nudeln, Reis, Soßen, Backen)', orderIndex: 5 },
    { id: 'rw-6', number: 6, name: '6. Konserven, Fertiggerichte & Suppen', orderIndex: 6 },
    { id: 'rw-7', number: 7, name: '7. Süßwaren & Knabberartikel', orderIndex: 7 },
    { id: 'rw-8', number: 8, name: '8. Getränke', orderIndex: 8 },
    { id: 'rw-9', number: 9, name: '9. Drogerie & Kosmetik', orderIndex: 9 },
    { id: 'rw-10', number: 10, name: '10. Tiernahrung & Haushalt', orderIndex: 10 },
    { id: 'rw-11', number: 11, name: '11. Tiefkühlkost & Eis', orderIndex: 11 }
  ],
  'aldi': [
    { id: 'al-1', number: 1, name: '1. Obst & Gemüse', orderIndex: 1 },
    { id: 'al-2', number: 2, name: '2. Brot & Backwaren / Backshop', orderIndex: 2 },
    { id: 'al-3', number: 3, name: '3. Kühlung & Molkereiprodukte', orderIndex: 3 },
    { id: 'al-4', number: 4, name: '4. Fleisch, Wurst & Frischtheke', orderIndex: 4 },
    { id: 'al-5', number: 5, name: '5. Trockensortiment, Nudeln & Konserven', orderIndex: 5 },
    { id: 'al-6', number: 6, name: '6. Getränke & Säfte', orderIndex: 6 },
    { id: 'al-7', number: 7, name: '7. Süßwaren & Knabberartikel', orderIndex: 7 },
    { id: 'al-8', number: 8, name: '8. Drogerie, Haushaltswaren & Tiernahrung', orderIndex: 8 },
    { id: 'al-9', number: 9, name: '9. Tiefkühlkost (TK)', orderIndex: 9 }
  ],
  'lidl': [
    { id: 'li-1', number: 1, name: '1. Obst & Gemüse', orderIndex: 1 },
    { id: 'li-2', number: 2, name: '2. Backshop & Frische-Backwaren', orderIndex: 2 },
    { id: 'li-3', number: 3, name: '3. Frischetheke, Fleisch & Wurst', orderIndex: 3 },
    { id: 'li-4', number: 4, name: '4. Milchprodukte & Molkereiprodukte', orderIndex: 4 },
    { id: 'li-5', number: 5, name: '5. Trockensortiment (Nudeln, Reis, Konserven)', orderIndex: 5 },
    { id: 'li-6', number: 6, name: '6. Süßwaren, Snacks & Knabberartikel', orderIndex: 6 },
    { id: 'li-7', number: 7, name: '7. Getränke', orderIndex: 7 },
    { id: 'li-8', number: 8, name: '8. Drogerie, Haushalt & Tiernahrung', orderIndex: 8 },
    { id: 'li-9', number: 9, name: '9. Tiefkühlkost (TK)', orderIndex: 9 },
    { id: 'li-10', number: 10, name: '10. Non-Food Aktionswaren', orderIndex: 10 }
  ],
  'netto': [
    { id: 'ne-1', number: 1, name: '1. Obst & Gemüse', orderIndex: 1 },
    { id: 'ne-2', number: 2, name: '2. Backshop & Brot', orderIndex: 2 },
    { id: 'ne-3', number: 3, name: '3. Molkereiprodukte & Käse', orderIndex: 3 },
    { id: 'ne-4', number: 4, name: '4. Fleisch, Wurst & Geflügel', orderIndex: 4 },
    { id: 'ne-5', number: 5, name: '5. Grundnahrungsmittel, Nudeln & Konserven', orderIndex: 5 },
    { id: 'ne-6', number: 6, name: '6. Süßwaren & Knabberartikel', orderIndex: 6 },
    { id: 'ne-7', number: 7, name: '7. Getränke', orderIndex: 7 },
    { id: 'ne-8', number: 8, name: '8. Drogerie, Tiernahrung & Haushalt', orderIndex: 8 },
    { id: 'ne-9', number: 9, name: '9. Tiefkühlkost', orderIndex: 9 }
  ],
  'fressnapf': [
    { id: 'fn-1', number: 1, name: '1. Hundefutter (Nassfutter & Dosen)', orderIndex: 1 },
    { id: 'fn-2', number: 2, name: '2. Hundefutter (Trockenfutter & Säcke)', orderIndex: 2 },
    { id: 'fn-3', number: 3, name: '3. Hundesnacks, Leckerlies & Knabberartikel', orderIndex: 3 },
    { id: 'fn-4', number: 4, name: '4. Katzenfutter (Nassfutter & Beutel / Schalen)', orderIndex: 4 },
    { id: 'fn-5', number: 5, name: '5. Katzenfutter (Trockenfutter & große Säcke)', orderIndex: 5 },
    { id: 'fn-6', number: 6, name: '6. Katzenstreu & Toiletten', orderIndex: 6 },
    { id: 'fn-7', number: 7, name: '7. Katzensnacks & Spielzeug', orderIndex: 7 },
    { id: 'fn-8', number: 8, name: '8. Kleintiere & Nager (Futter & Streu)', orderIndex: 8 },
    { id: 'fn-9', number: 9, name: '9. Aquaristik & Vögel (Futter & Zubehör)', orderIndex: 9 },
    { id: 'fn-10', number: 10, name: '10. Hundezubehör, Leinen, Betten & Pflege', orderIndex: 10 }
  ],
  'edeka': [
    { id: 'ed-1', number: 1, name: '1. Obst & Gemüse', orderIndex: 1 },
    { id: 'ed-2', number: 2, name: '2. Backshop & Frische-Brot', orderIndex: 2 },
    { id: 'ed-3', number: 3, name: '3. Frischetheke (Fleisch, Wurst & Käse)', orderIndex: 3 },
    { id: 'ed-4', number: 4, name: '4. Molkereiprodukte & Kühlung', orderIndex: 4 },
    { id: 'ed-5', number: 5, name: '5. Trockensortiment (Nudeln, Reis, Soßen)', orderIndex: 5 },
    { id: 'ed-6', number: 6, name: '6. Getränke', orderIndex: 6 },
    { id: 'ed-7', number: 7, name: '7. Drogerie & Haushalt', orderIndex: 7 },
    { id: 'ed-8', number: 8, name: '8. Tiefkühlkost & Eis', orderIndex: 8 }
  ],
  'rossmann': [
    { id: 'ro-1', number: 1, name: '1. Haare & Körperpflege', orderIndex: 1 },
    { id: 'ro-2', number: 2, name: '2. Gesicht, Kosmetik & Make-up', orderIndex: 2 },
    { id: 'ro-3', number: 3, name: '3. Zahnpflege & Mundhygiene', orderIndex: 3 },
    { id: 'ro-4', number: 4, name: '4. Baby, Kind & Windeln', orderIndex: 4 },
    { id: 'ro-5', number: 5, name: '5. Haushaltswaren & Reinigungsmittel', orderIndex: 5 },
    { id: 'ro-6', number: 6, name: '6. Papier & Hygiene (Toilettenpapier, Küchenrolle)', orderIndex: 6 },
    { id: 'ro-7', number: 7, name: '7. Lebensmittel, Bio & Snacks', orderIndex: 7 },
    { id: 'ro-8', number: 8, name: '8. Gesundheit, Wellness & Kasse', orderIndex: 8 }
  ]
};

const COMMON_UNITS = ['Stk.', 'Einzelflasche', 'Packung', '4er Pack', '6er Pack', 'Flasche', 'Dose', 'Beutel', 'Tüte', 'Becher', 'Glas', 'Tube', 'Rolle', 'Schale', 'Bund', 'Kiste', 'Laib', 'Sack', 'Tafel', 'ml', 'l', 'g', 'kg'];
const EMOJI_PALETTE = ['🛒', '📋', '🍎', '🥦', '🥩', '🧀', '🍞', '🥤', '🍺', '🍷', '🍫', '🍿', '🥫', '☕', '🍕', '🧴', '🧻', '🐱', '🐶', '🌱', '🔨', '🏠', '🎉', '🧺', '💊', '🎂', '🚗', '⭐', '⚡', '🎁', '🏖️', '🎒'];

const RECIPE_CATEGORIES = [
  { name: 'Schnelle Gerichte', icon: '⚡', query: 'schnelle gerichte' },
  { name: 'Fleischgerichte', icon: '🥩', query: 'fleischgerichte' },
  { name: 'Günstige Gerichte', icon: '💶', query: 'günstige gerichte' },
  { name: 'Suppengerichte', icon: '🥣', query: 'suppen' },
  { name: 'High protein Rezepte', icon: '💪', query: 'high protein' },
  { name: 'Vegetarisch', icon: '🌱', query: 'vegetarisch' },
  { name: 'Beliebte Rezepte', icon: '⭐', query: 'beliebte rezepte' }
];

const PERSONAL_SEED = [
  ["Emma tabs Somat", 12, 8.99, 0, "Packung"], ["Toilettenpapier", 12, 2.95, 0, "Packung"],
  ["Lenor Weichspüler", 12, 2.59, 0, "Flasche"], ["Seife Sagrotan", 12, 1.45, 0, "Flasche"],
  ["Colgate Zahnpasta", 12, 1.45, 0, "Tube"], ["Fanta Penny", 3, 0.65, 0.25, "Einzelflasche"],
  ["Coca-Cola", 3, 1.39, 0.25, "Einzelflasche"], ["Lucky cat Nassfutter 15 stk", 12, 3.19, 0, "Packung"],
  ["Coca-Cola Zero", 3, 1.39, 0.25, "Einzelflasche"], ["Sprite", 6, 1.39, 0.25, "6er Pack"],
  ["Selter", 12, 1.74, 0.25, "Einzelflasche"], ["Nivea Duschgel", 12, 2.19, 0, "Flasche"],
  ["Bruno banani", 6, 2.99, 0, "Tube"], ["Toilettenduftstein", 6, 1.99, 0, "Stk."],
  ["Wahre Schätze Pflegespülung", 12, 2.49, 0, "Flasche"], ["Shampoo Head& +Shoulders", 6, 4.99, 0, "Flasche"],
  ["Haarshampoo Schauma Isabel", 12, 2.49, 0, "Flasche"], ["Yumm yumm", 6, 0.49, 0, "Packung"],
  ["Gouda jung Scheiben", 7, 2.99, 0, "Packung"], ["Taschentücher Box", 12, 1.85, 0, "Packung"],
  ["Tomatenketchup", 5, 1.29, 0, "Flasche"], ["Fischstäbchen (15er)", 1, 2.99, 0, "Packung"],
  ["Energy Papa groß", 3, 1.49, 0.25, "Dose"], ["Energy Julia", 3, 1.49, 0.25, "Dose"],
  ["Hähnchenschenkel Mama", 5, 4.99, 0, "Tüte"], ["Kleine Pizza Isabel", 1, 3.49, 0, "Packung"],
  ["Rasierklingen", 6, 0.00, 0, "Packung"], ["Stumpenkerzen", 6, 5.49, 0, "Stk."],
  ["Raumduft", 6, 0.00, 0, "Packung"], ["Pants Isabel", 12, 5.99, 0, "Packung"], ["Pants", 12, 5.99, 0, "Packung"],
  ["Wäschepods Ariel 41", 12, 0.00, 0, "Packung"], ["Pants Mama", 12, 9.49, 0, "Packung"],
  ["Haargel (Kleber)", 12, 4.99, 0, "Tube"], ["Instant Kaffee", 4, 6.49, 0, "Packung"],
  ["Raumduft Stecker", 12, 4.99, 0, "Packung"], ["Raumduft Aroma Öl", 12, 5.99, 0, "Packung"],
  ["Bruno banani Duschgel", 12, 2.99, 0, "Tube"],
  ["Thai Chef Huhn", 6, 0.59, 0, "Packung"],
  ["JPS CLASS.RED", 13, 10.00, 0, "Packung"],
  ["Lucky Cat 2 kg", 12, 2.29, 0, "Packung"],
  ["HACKFLEISCH XXL", 5, 6.49, 0, "Packung"],
  ["BIERSCHINKEN", 5, 1.29, 0, "Packung"],
  ["FLEISCHWURST", 5, 2.69, 0, "Packung"],
  ["SCH. ZWIEBELMETT", 5, 1.79, 0, "Packung"],
  ["FRISCHKAESE KRAE", 7, 0.99, 0, "Packung"],
  ["Weizen Sandwich", 10, 1.19, 0, "Packung"],
  ["Mango", 1, 0.99, 0, "Stk."],
  ["Kartoffeln 2,5kg", 4, 3.49, 0, "Tüte"],
  ["Karotten", 1, 1.49, 0, "Packung"],
  ["Möhren", 1, 1.49, 0, "Packung"],
  ["EIER BODENHALT.", 6, 4.19, 0, "Packung"],
  ["MEGGLE UNGESALZ", 9, 2.29, 0, "Packung"],
  ["Greenl. Spinat", 11, 1.89, 0, "Packung"],
  ["Greenl. Rahmgemü", 11, 1.99, 0, "Packung"],
  ["Gnuss Pur Spiral", 6, 1.99, 0, "Packung"],
  ["Maggi Fix", 6, 1.09, 0, "Packung"],
  ["Cornichons", 8, 0.99, 0, "Glas"],
  ["EXOTIC LIMONADE", 3, 0.39, 0.25, "Einzelflasche"],
  ["Eistee Wildkirs.", 3, 1.99, 0.25, "Einzelflasche"],
  ["RB SUMMER", 3, 0.99, 0.25, "Dose"],
  ["SW-Minuten Steak", 5, 3.19, 0, "Packung"],
  ["SW-Geschn. Gyros", 5, 3.99, 0, "Packung"],
  ["Hä-Gyros Zwiebel", 5, 3.99, 0, "Packung"],
  ["XXL WIENER WUER.", 9, 6.79, 0, "Packung"],
  ["Hot Dog Rolls", 10, 0.99, 0, "Packung"],
  ["KRAUTSALAT", 7, 1.59, 0, "Packung"],
  ["Chiquita Bananen", 1, 2.49, 0, "kg"],
  ["Nektarinen", 1, 1.49, 0, "Packung"],
  ["SPEISEQUARK MAG.", 7, 1.19, 0, "Packung"],
  ["CREME FRAICHE", 7, 0.99, 0, "Becher"],
  ["LF Langkornreis", 6, 1.59, 0, "Packung"],
  ["SALTLETTS SESAM", 2, 2.29, 0, "Packung"],
  ["COKE VANILLA", 3, 0.79, 0.25, "Einzelflasche"],
  ["COMET COLA 0Z", 3, 3.90, 0, "Flasche"],
  ["RED BULL APRICOT", 3, 0.99, 0.25, "Dose"],
  ["MONSTER ORIGINAL", 3, 1.49, 0.25, "Dose"],
  ["Hä.-Brustfilet", 5, 6.79, 0, "Packung"],
  ["SCHINKENMETTWURS", 5, 1.69, 0, "Packung"],
  ["HINTERSCHINKEN", 5, 1.49, 0, "Packung"],
  ["HAEHNCHENBRUST", 5, 1.59, 0, "Packung"],
  ["GOUDA JUNG SCHB.", 7, 1.65, 0, "Packung"],
  ["San Fab. Mozzare", 7, 0.85, 0, "Packung"],
  ["Börekst griech K", 10, 0.79, 0, "Packung"],
  ["Knusperst. Hä.", 11, 0.79, 0, "Packung"],
  ["Zimtröllchen", 10, 2.49, 0, "Packung"],
  ["BITEBROWN", 2, 1.99, 0, "Packung"],
  ["Chinois Schoko", 10, 1.99, 0, "Packung"],
  ["MOIN KAKAO DRINK", 9, 0.95, 0, "Packung"],
  ["ZAZIKI", 7, 0.65, 0, "Becher"],
  ["Huberti Sardinen", 8, 1.99, 0, "Dose"],
  ["TURBO AB TABAK", 13, 23.70, 0, "Stk."],
  ["DUFTKERZE", 12, 3.49, 0, "Stk."],
  ["BITEZITRONE", 2, 1.99, 0, "Packung"],
  ["Frischeiwaffel", 10, 1.59, 0, "Packung"],
  ["Spitzkohl", 1, 1.49, 0, "kg"],
  ["RB Green Edition", 3, 1.49, 0.25, "Dose"],
  ["TURBO HUELSEN PA", 12, 1.19, 0, "Packung"],
  ["TEELICHTE 30ER", 12, 2.00, 0, "Packung"],
  ["SW Bratwurst", 5, 2.49, 0, "Packung"],
  ["WIENER KAESE", 9, 3.99, 0, "Packung"],
  ["LEBERWURST", 5, 1.79, 0, "Packung"],
  ["GEFL. LEBERWURST", 5, 1.39, 0, "Packung"],
  ["RINDSMETTWURST", 5, 2.59, 0, "Packung"],
  ["SPORTLERSALAMI", 5, 1.59, 0, "Packung"],
  ["NORDSEEKAESE", 7, 2.70, 0, "Packung"],
  ["Landfreund Knöde", 6, 0.99, 0, "Packung"],
  ["LF Semmelknödel", 6, 0.79, 0, "Packung"],
  ["KARTOF.FL.PUEREE", 6, 1.19, 0, "Packung"],
  ["Knorr Soße", 6, 1.59, 0, "Packung"],
  ["Greenland Rotk.", 11, 1.19, 0, "Packung"],
  ["CHIPSFRISCH", 2, 1.99, 0, "Packung"],
  ["Coca Cola Zero", 3, 6.66, 0, "Flasche"],
  ["BIC FEUERZEUG Pk", 12, 1.59, 0, "Stk."]
];

const INITIAL_FAVORITE_NAMES = [
  "Emma tabs Somat", "Toilettenpapier", "Lenor Weichspüler", "Seife Sagrotan",
  "Colgate Zahnpasta", "Fanta Penny", "Coca-Cola", "Lucky cat Nassfutter 15 stk",
  "Coca-Cola Zero", "Sprite", "Selter", "Nivea Duschgel", "Bruno banani",
  "Toilettenduftstein", "Wahre Schätze Pflegespülung", "Shampoo Head& +Shoulders",
  "Haarshampoo Schauma Isabel", "Yumm yumm", "Gouda jung Scheiben", "Taschentücher Box",
  "Tomatenketchup", "Fischstäbchen (15er)", "Energy Papa groß", "Energy Julia",
  "Hähnchenschenkel Mama", "Kleine Pizza Isabel", "Rasierklingen", "Stumpenkerzen",
  "Raumduft", "Pants Isabel", "Pants", "Wäschepods Ariel 41", "Pants Mama",
  "Haargel (Kleber)", "Instant Kaffee", "Raumduft Stecker", "Raumduft Aroma Öl", "Bruno banani Duschgel"
];

const BROCHURES = [
  { store: 'Penny Markt', branch: 'Schwarzenbek (Hamburger Str. 18)', badge: 'Unser Markt', link: 'https://www.penny.de/angebote', color: '#CC0000', icon: '🛒' },
  { store: 'Lidl', branch: 'Schwarzenbek (Compestraße)', badge: 'Wochenprospekt', link: 'https://www.lidl.de/c/billiger-katalog-kw/s10007556', color: '#0050AA', icon: '🏷️' },
  { store: 'Rewe', branch: 'Schwarzenbek', badge: 'Wochenangebote', link: 'https://www.rewe.de/angebote/', color: '#CC0000', icon: '🍎' },
  { store: 'Aldi Nord', branch: 'Schwarzenbek (Grabauer Str. 2)', badge: 'Angebote', link: 'https://www.aldi-nord.de/angebote.html', color: '#002B49', icon: '⭐' },
  { store: 'Rossmann', branch: 'Schwarzenbek (Europaplatz)', badge: 'Drogerie & Baby', link: 'https://www.rossmann.de/de/angebote', color: '#E30613', icon: '💄' },
  { store: 'Fressnapf', branch: 'Schwarzenbek / Umgebung', badge: 'Tierbedarf', link: 'https://www.fressnapf.de/angebote/', color: '#00539F', icon: '🐾' }
];
